"""Locks the canonical fixtures (tests/fixtures/*.bin) against the
golden tests/fixtures/MANIFEST.json and checks tools/verify_cin2.py's
verdict on each. This manifest is NOT regenerated by test failures --
a mismatch here is a real regression (either the fixture generator or
the verifier/format changed unexpectedly) and must be investigated, not
silenced by re-running generate_fixtures.py."""
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))
import verify_cin2  # noqa: E402

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
MANIFEST = json.loads((FIXTURES_DIR / "MANIFEST.json").read_text())


def _check_entry(entry):
    path = FIXTURES_DIR / entry["file"]
    raw = path.read_bytes()
    assert len(raw) == entry["size"], f"{entry['file']}: size drifted from manifest"
    assert hashlib.sha256(raw).hexdigest() == entry["sha256"], \
        f"{entry['file']}: sha256 drifted from manifest -- fixture changed unexpectedly"
    return path


def test_good_fixtures_match_manifest_and_pass():
    for name, entry in MANIFEST["good"].items():
        path = _check_entry(entry)
        result = verify_cin2.verify(path)
        assert result["ok"] == entry["expected_verifier_ok"], \
            f"{name}: verifier ok={result['ok']}, expected {entry['expected_verifier_ok']}: " \
            f"{result.get('errors')}"


def test_bad_fixtures_match_manifest():
    for name, entry in MANIFEST["bad"].items():
        path = _check_entry(entry)
        result = verify_cin2.verify(path)
        if name in ("trailing_data",):
            assert result["ok"], f"{name}: expected PASS-with-warning"
            assert result["warnings"], f"{name}: expected a warning about trailing data"
        elif name == "v1_synthetic":
            # No CIN2 magic at all -- correctly refused as v2, which is
            # the only thing this fixture is used to prove here.
            assert not result["ok"]
            assert "magic" in result["errors"][0]
        else:
            assert not result["ok"], f"{name}: expected verifier to reject this file"
            assert result["errors"], f"{name}: rejection with no recorded error message"


def test_frame_count_variants_have_expected_counts():
    for name, expected in (("one_frame_movie", 1), ("four_frame_movie", 4),
                            ("five_frame_movie", 5), ("short_24_1", 24),
                            ("short_24000_1001", 24), ("resume_fixture", 30)):
        entry = MANIFEST["good"][name]
        path = FIXTURES_DIR / entry["file"]
        result = verify_cin2.verify(path)
        assert result["header"]["frame_count"] == expected, name


def test_24_1_and_24000_1001_have_distinct_durations():
    r24 = verify_cin2.verify(FIXTURES_DIR / MANIFEST["good"]["short_24_1"]["file"])
    r24000 = verify_cin2.verify(FIXTURES_DIR / MANIFEST["good"]["short_24000_1001"]["file"])
    assert r24["expected_duration_s"] != r24000["expected_duration_s"]
    assert abs(r24["expected_duration_s"] - 1.0) < 1e-9
    assert abs(r24000["expected_duration_s"] - 24 * 1001 / 24000) < 1e-9
