#ifndef CINEMA_RENDER_V2_H
#define CINEMA_RENDER_V2_H

/* Renderer selection for player_v2.c's per-frame scale-up. Set via the
 * Makefile (CFLAGS += -DCINEMA_RENDERER=CINEMA_RENDERER_FIXED_C, say),
 * not by editing this file. Defaults to the original, hardware-proven
 * GraphX call if the build doesn't override it, so an ordinary `make`
 * behaves exactly as it always has.
 *
 *   CINEMA_RENDERER_GRAPHX    -- gfx_ScaledSprite_NoClip(). The control.
 *                                Hardware-proven; this is what commit
 *                                33fac1c shipped. Default.
 *   CINEMA_RENDERER_FIXED_C   -- render_scaled_fixed_c() below: a plain
 *                                C implementation specialized for
 *                                Cinema's one fixed operation (160x96
 *                                8bpp -> 320x192 at (0,24), always).
 *                                Host-tested for pixel correctness
 *                                against a naive reference; not yet
 *                                tested on real hardware.
 *   CINEMA_RENDERER_FIXED_ASM -- render_scaled_fixed_asm() (see
 *                                src/render_v2_asm.s): the same
 *                                algorithm, generated by compiling
 *                                render_scaled_fixed_c with the real CE
 *                                toolchain and checking the resulting
 *                                assembly in directly, reviewed by
 *                                hand. UNVERIFIED BY EXECUTION -- there
 *                                is no ROM/emulator/hardware in this
 *                                development environment, so this path
 *                                has never actually run. Opt-in only;
 *                                do not treat it as trustworthy without
 *                                a real test first.
 */
#define CINEMA_RENDERER_GRAPHX    0
#define CINEMA_RENDERER_FIXED_C   1
#define CINEMA_RENDERER_FIXED_ASM 2

#ifndef CINEMA_RENDERER
#define CINEMA_RENDERER CINEMA_RENDERER_GRAPHX
#endif

/* Fixed 160x96 (one 8bpp palette-index byte per pixel, see
 * CINEMA_V2_WIDTH/HEIGHT) -> 320x192 2x nearest-neighbor scale-up,
 * drawn at destination (0, 24) into GraphX's *current* draw buffer
 * (whichever gfx_SetDraw() last selected -- via the public gfx_vbuffer
 * macro, not an assumed fixed address). src must point at exactly
 * CINEMA_V2_WIDTH * CINEMA_V2_HEIGHT bytes (a frame_slot_t's sprite
 * data, past its 2-byte width/height header -- see slot_sprite() in
 * player_v2.c). See src/render_v2.c for the full rationale. */
void render_scaled_fixed_c(const unsigned char *src);

#if CINEMA_RENDERER == CINEMA_RENDERER_FIXED_ASM
/* Same contract as render_scaled_fixed_c -- see src/render_v2_asm.s for
 * the unverified-by-execution caveat before enabling this. */
void render_scaled_fixed_asm(const unsigned char *src);
#endif

#endif
